### ISSUE TITLE
4 Лаба Код

### ISSUE THREAD

**Issue by oleg-tgn** [lazaryan/OAiP_labs_Lazaryan#11]
1) `ExistFile() ` - функции называем с маленькой буквы
-> `existFile() `

2) Помимо проверки на файла функция ExistFile еще и завершает работу, что может быть довольно неожиданно для другого программиста, т.к. это довольно глобальное дейтсвие

Так же мы не сможем использовать эту функцию повторно, если в друго программе нужно будет проверить наличие файла, и, например, попросить пользователя уточнить путь к файлу, который он возможно просто неверно ввел

Тут лучше поменять логику следующим образом переименовать функцию в isExistFile() и пусть она возвращает true или false. Если вернет false - выход сделаем в главной функции

3) ChangeString - тут убер-мега-функция которая делает очень много вещей
давайте ее разобьем на несколько

во первых сделаем 
- отдельную функцию, которая заменяет данные уже в считанной строке
- отдельную функцию, которая выводит полученную строку в файл

Т.е. сделаем так

main()  {
   открываем_файл
   если (!файлСуществует) {
      выходим()
   }
   переменная_строки = фукция_считывания_файла()
   функция_замены_символов()
   функция_вывода_строки()
}

Функцию замены символа так же можно разбить

функция_преобразования_строки() {
    цикл идущий по символам {
        если (функция_которая_проверяет_что_это_то_самое_место() == true) {
            функция_замены()
        }
    }
}

**Comment by oleg-tgn** [comment]
Да, и я поздно прочитал предупреждение))

**Comment by lazaryan** [comment]
не там
